// admin ap1

@url =  http://localhost:8000/api/v1

POST {{url}}/admin/register
Content-Type: application/json

{
"address": "b@gmail.com",
"confirmPassword": "1234",
"email": "tseyan6ig@gmail.com",
"fname": "tseyang986@gmail.com",
"lname": "ds",
"password": "11234",
"phoneno": "9869183095"
}