// admin ap1

@url =  http://localhost:8000/api/v1

POST {{url}}/admin/register
Content-Type: application/json

{
"address": "b@gmail.com",
"email": "tseyang98611@gmail.com",
"fname": "tsering",
"lname": "lama",
"password": "1234"


}


### login
POST {{url}}/admin/login
Content-Type: application/json

{
"email": "tseyang9861@gmail.com",
"password": "1234"


}

